### ISSUE TITLE
FireDept in my garage

### ISSUE THREAD

**Issue by ArcaneZaros** [LividFizz/destinationrp#11]
![image](https://user-images.githubusercontent.com/57280704/68194104-a1a76400-ff71-11e9-8808-6d5e134c0cd2.png)
I don't know why this is in my garage for a few days me (zach) and rooster aka Curtisn341 were firefighters but this wasnt in my garage until maybe 20-30 minutes ago

**Comment by LividFizz** [comment]
This was removed from your garage. Thank you for the report
