### ISSUE TITLE
Feature Request -  Only work while there is no EMS / Ambulance online

### ISSUE THREAD

**Issue by it-junkiez** [LividFizz/destinationrp#12]
Hi,

Sorry i couldnt find anywhere to put a feature request. i'm fairly new to github. 

As discussed on the FiveM forums, would it be possible to make it so that it's configurable to work only when there is x numbers of EMS online. ideally 0 but adding that variable would be a nice touch! 

Thanks 

Lee

**Comment by LividFizz** [comment]
Grandmas house is not meant for no EMS online. It’s meant for criminals who wouldn’t like to show their face at pillbox or be treated by EMS, giving out their name ect. This will not be worked on by me, but if someone would like to PR this they can.
