### ISSUE TITLE
Can't revive

### ISSUE THREAD

**Issue by LilEligius** [LividFizz/destinationrp#2]
Cant revive only head on drp-grandmas

**Comment by LividFizz** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

Please follow this format above ^

**Comment by LilEligius** [comment]
For example, if you are dead at the point, when you hit the "E" it does not revive you. Sorry, I do not speak a lot of english

**Comment by HurtHurt** [comment]
im having the same problem as him

**Comment by LividFizz** [comment]
esx_ambulancejob? both of you?

**Comment by LilEligius** [comment]
Yes

**Comment by LividFizz** [comment]
client/main.lua in esx_ambulancejob line 104. Remove the DisableControlAction of "E" there. Then restart your servers. Least thats the correct line on the esx_ambulancejob github.

**Comment by HurtHurt** [comment]
Alright I’ll try that thank you.

**Comment by LividFizz** [comment]
is this issue resolved?

**Comment by LilEligius** [comment]
Yes, prefect thx! ;D
