### ISSUE TITLE
Cant lock double doors

### ISSUE THREAD

**Issue by Dennis-NL** [LividFizz/destinationrp#5]
Its not possible to lock double doors. It only locks and unlocks one door

**Comment by LividFizz** [comment]
You can’t do that with regular esx doorlock. That’s a great suggestion though. I can work on that.

**Comment by Dennis-NL** [comment]
You can sort of. If the 2 doors are in range it wil open and close both of them

**Comment by LividFizz** [comment]
well, does it work or not? as intended that is.
