### ISSUE TITLE
Banks eating lockpicks

### ISSUE THREAD

**Issue by ArcaneZaros** [LividFizz/destinationrp#7]
Just tried to do a bank and it ate both of my lockpicks

**Comment by ArcaneZaros** [comment]
It was at legion square bank

**Comment by ElPumpo** [comment]
?

**Comment by LividFizz** [comment]
It works perfectly fine.

**Comment by ArcaneZaros** [comment]
Unless there is a certain spot at the door to do it, it straight up made 2 lockpicks disappear

**Comment by LividFizz** [comment]
You lose lockpicks if you fail.

**Comment by ArcaneZaros** [comment]
It didnt give me the chance to try

**Comment by LividFizz** [comment]
This was fixed in the most recent patch.
