### ISSUE TITLE
 Scipt does not like job changing

### ISSUE THREAD

**Issue by jrlpez** [LividFizz/destinationrp#9]
As per what was mentioned on FiveM forums. 

Bug found in conjunction with esx_duty. If police (or any job that has an off duty mode) 'wakes up' in the city off duty, once they are on duty they cannot access these doors until they have a nap. Vice versa if they are on duty and go off duty, where they shouldn't be able to access the doors, they can until they reconnect.

**Comment by LividFizz** [comment]
Ill take a look into this and try to better improve it.

**Comment by LividFizz** [comment]
This has been fixed, pull the newest commit
